import type { Metadata } from 'next';
import './globals.css';
import NextAuthProvider from '@/lib/nextauth/next-auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>
          <div className={'flex h-screen w-full items-center justify-center'}>
            {children}
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
